SELECT T.CUSTOMER_ID,T.CUSTOMER_NAME, T.PRODUCT_ID, T.PRODUCT_NAME, 
CASE WHEN A.QUANTITY IS NOT NULL THEN A.QUANTITY ELSE 0 END AS QUANTITY, 
CASE WHEN A.DOLLAR_VALUE IS NOT NULL THEN A.DOLLAR_VALUE ELSE 0 END AS DOLLAR_VALUE
FROM
(SELECT DISTINCT A.CUSTOMER_ID,A.CUSTOMER_NAME, B.PRODUCT_ID, B.PRODUCT_NAME FROM CUSTOMER A
CROSS JOIN PRODUCT B) T
LEFT JOIN 
(SELECT S.CUSTOMER_ID,S.PRODUCT_ID,SUM(S.QUANTITY) AS QUANTITY, SUM(S.QUANTITY*S.PRICE) AS DOLLAR_VALUE FROM SALE S
GROUP BY S.CUSTOMER_ID,S.PRODUCT_ID) A
ON A.CUSTOMER_ID=T.CUSTOMER_ID AND A.PRODUCT_ID=T.PRODUCT_ID
ORDER BY T.CUSTOMER_ID,A.DOLLAR_VALUE;