SELECT T.CATEGORY_ID,T.CATEGORY_NAME, T.STATE_ID, T.STATE_NAME, 
CASE WHEN A.quantity_sold IS NOT NULL THEN A.quantity_sold ELSE 0 END AS quantity_sold, 
CASE WHEN A.dollar_value IS NOT NULL THEN A.dollar_value ELSE 0 END AS dollar_value
FROM
(SELECT DISTINCT A.CATEGORY_ID,A.CATEGORY_NAME, B.STATE_ID, B.STATE_NAME FROM CATEGORY A
CROSS JOIN STATE B) T
LEFT JOIN 
(SELECT CT.CATEGORY_ID,CT.CATEGORY_NAME,ST.STATE_ID,ST.STATE_NAME,sum(S.QUANTITY) AS quantity_sold,SUM(S.QUANTITY*S.PRICE) AS dollar_value FROM SALE S
JOIN PRODUCT P ON S.PRODUCT_ID=P.PRODUCT_ID
JOIN CUSTOMER CU ON S.CUSTOMER_ID=CU.CUSTOMER_ID
JOIN CATEGORY CT ON P.CATEGORY_ID=CT.CATEGORY_ID
JOIN STATE ST ON ST.STATE_ID=CU.STATE_ID
GROUP BY CT.CATEGORY_ID,ST.STATE_ID) A
ON A.CATEGORY_ID=T.CATEGORY_ID AND A.STATE_ID=T.STATE_ID
ORDER BY T.STATE_ID;