SELECT A.CATEGORY_ID, A.CUSTOMER_ID,
CASE WHEN B.QUANTITY IS NOT NULL THEN B.QUANTITY ELSE 0 END AS QUANTITY,
CASE WHEN B.DOLLAR_VALUE IS NOT NULL THEN B.DOLLAR_VALUE ELSE 0 END AS DOLLAR_VALUE
FROM
(SELECT DISTINCT CT.CATEGORY_ID,CU.CUSTOMER_ID FROM CUSTOMER CU
CROSS JOIN CATEGORY CT) A
LEFT JOIN 
(SELECT P.CATEGORY_ID,S.CUSTOMER_ID,SUM(S.QUANTITY) AS QUANTITY, SUM(S.QUANTITY*S.PRICE) AS DOLLAR_VALUE FROM SALE S
JOIN PRODUCT P ON S.PRODUCT_ID=P.PRODUCT_ID
GROUP BY S.CUSTOMER_ID,P.CATEGORY_ID) B
ON B.CATEGORY_ID=A.CATEGORY_ID AND B.CUSTOMER_ID=A.CUSTOMER_ID
WHERE 
A.CATEGORY_ID IN 
(SELECT P.CATEGORY_ID FROM SALE S
JOIN PRODUCT P ON P.PRODUCT_ID=S.PRODUCT_ID
GROUP BY P.CATEGORY_ID
ORDER BY SUM(S.QUANTITY*S.PRICE) DESC
LIMIT 20
)
AND
A.CUSTOMER_ID IN
(SELECT S.CUSTOMER_ID FROM SALE S
GROUP BY S.CUSTOMER_ID
ORDER BY SUM(S.QUANTITY*S.PRICE) DESC
LIMIT 20
);
